In [4]:
import numpy as np

In [5]:
a = [0,1,2,3,4,5]*100000
b = np.array(a)
len(a)

600000

In [6]:
b*2

array([ 0,  2,  4, ...,  6,  8, 10])

In [8]:
len(b)

600000

In [11]:
%%timeit -n10
[x*2 for x in a]

45.7 ms ± 2.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
%%timeit -n10
b*2

2.14 ms ± 463 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [14]:
%%timeit -n1
sum(a)

5.93 ms ± 1.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
%%timeit -n1
b.sum()

356 µs ± 68.7 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [16]:
a = np.array([[0,1],[2,3],[4,5]])
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
type(a)

numpy.ndarray

In [18]:
a*5

array([[ 0,  5],
       [10, 15],
       [20, 25]])

In [22]:
b = np.array([[2,3],[1,2], [0,1]])

In [23]:
b*a

array([[0, 3],
       [2, 6],
       [0, 5]])

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [29]:
x = np.arange(20)

In [30]:
x.shape

(20,)

In [34]:
x.shape = (4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [43]:
x.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [44]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)